### ISSUE TITLE
Persistence history

### ISSUE THREAD

**Issue by sassanh** [svermeulen/nvim-yoink#3]
It'd be nice if the history could persist in new sessions of vim. If you don't have any plans for it I can work on it.

**Comment by svermeulen** [comment]
How were you picturing that working?  Using NeoVim's Shada feature somehow?  Or loading from a custom file during VimEnter and then saving that out during VimLeave?  I'd assume also it would be off by default

**Comment by sassanh** [comment]
I was thinking about a file (as far as I remember that's how it worked in easyclip) but ShaDa seems to be better option. I agree it should be off by default.

**Comment by svermeulen** [comment]
Ok I think this should work now with `g:yoinkSavePersistently` set to 1

**Comment by sassanh** [comment]
@svermeulen Unfortunately it's not working for me.

**Comment by sassanh** [comment]
Seems like you forgot to commit it, cause the letters sequence `persi` is only used in `README.md`

**Comment by svermeulen** [comment]
Yep I missed something.  Try again now

**Comment by sassanh** [comment]
It's `'10,`, I can add `!` but I guess the implementation is better to work regardless of the value of `&shada`. What do you think?

**Comment by svermeulen** [comment]
I don't think there's another way to add custom data to shada other than global variables.  So I think users that want to use that feature just have to add `!`.  I'll add that to the docs

**Comment by sassanh** [comment]
That should be fine

**Comment by janbaer** [comment]
I'm not sure about the current support for sharing the yanked list in VIM? Is it supported in the meantime or not? I still get the warning that NEOVIM is required when I turn yoinkSavePersistently on.

**Comment by svermeulen** [comment]
I don't think VIM has this 'shada' feature that shared yank list depends on, so there isn't a clean way to  do it there.  So this feature is neovim only for now

**Comment by janbaer** [comment]
Thanks for the quick response. It's pitty that it's not supported because I liked the sharing feature in EasyClip very much. Hope to get also support in VIM soon. But thanks for your effort to provide us such a helpful plugin!

**Comment by svermeulen** [comment]
No problem glad you find it useful :)

**Comment by Freed-Wu** [comment]
persistence history only can be supported in nvim not vim...
it is regretful. can it be considered to realize this feature by other method? such as save history to an unique file?
thank you!

**Comment by svermeulen** [comment]
Any vim users are welcome to send a PR, but as a nvim user myself, I have no interest or motivation to add that
